name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: docker://reviewdog/action-golangci-lint:latest@sha256:9f8af9633d7a14d2100936693dc609249e13c29a352ce88fdc8a3d0aaadd8b26
        env:
          GITHUB_ACTION: reviewdog
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: file
          reporter: github-pr-check
          level: info
